---
#   - name: Install epel
#     yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present

   - name: Install base packages
     yum: name={{ item }} state=latest 
     with_items:
     - ntp
     - vim
     - screen
     - curl
     - git
