---
   - name: Install base packages
     apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
     with_items:
     - postgresql
     - postgresql-contrib
     - libpq-dev
     - python-psycopg2
